//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adhdb.language.en {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Dice {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dice() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("adhdb.language.en.Dice", typeof(Dice).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maybe?.
        /// </summary>
        internal static string CoinFlipStrMaybe {
            get {
                return ResourceManager.GetString("CoinFlipStrMaybe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        internal static string CoinFlipStrNo {
            get {
                return ResourceManager.GetString("CoinFlipStrNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes..
        /// </summary>
        internal static string CoinFlipStrYes {
            get {
                return ResourceManager.GetString("CoinFlipStrYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input..
        /// </summary>
        internal static string DoSimpleMathError {
            get {
                return ResourceManager.GetString("DoSimpleMathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result of **{0}{1}{2}** is **{3}**!.
        /// </summary>
        internal static string DoSimpleMathStrResult {
            get {
                return ResourceManager.GetString("DoSimpleMathStrResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;@{0}&gt; rolled the following:.
        /// </summary>
        internal static string RollMultipleStrBase {
            get {
                return ResourceManager.GetString("RollMultipleStrBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input an integer to throw a dice. For example: !1w20, !2w6, !3d20, !4d6 etc..
        /// </summary>
        internal static string RollMultipleStrError {
            get {
                return ResourceManager.GetString("RollMultipleStrError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result was changed by **{0}{1}**..
        /// </summary>
        internal static string RollMultipleStrManipulation {
            get {
                return ResourceManager.GetString("RollMultipleStrManipulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result is **{0}**!.
        /// </summary>
        internal static string RollMultipleStrResult {
            get {
                return ResourceManager.GetString("RollMultipleStrResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;@{0}&gt; rolled a **{1}**!.
        /// </summary>
        internal static string RollStrBase {
            get {
                return ResourceManager.GetString("RollStrBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input an integer to throw a dice. For example: !w20, !w6, !d20, !d6 etc..
        /// </summary>
        internal static string RollStrError {
            get {
                return ResourceManager.GetString("RollStrError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result was manipulated by **{0}{1}**..
        /// </summary>
        internal static string RollStrManipulation {
            get {
                return ResourceManager.GetString("RollStrManipulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result is **{0}**!.
        /// </summary>
        internal static string RollStrResult {
            get {
                return ResourceManager.GetString("RollStrResult", resourceCulture);
            }
        }
    }
}
