//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adhdb.language.en {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DSA {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DSA() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("adhdb.language.en.DSA", typeof(DSA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical hit! **{0}** damage!.
        /// </summary>
        internal static string CritDamage {
            get {
                return ResourceManager.GetString("CritDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error..
        /// </summary>
        internal static string CritError {
            get {
                return ResourceManager.GetString("CritError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical mistake! You forgot to put in a number to calculate..
        /// </summary>
        internal static string CritMissingNumber {
            get {
                return ResourceManager.GetString("CritMissingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to use at least five tropes, to generate an interesting character, including backstory..
        /// </summary>
        internal static string DisplayCharacterGeneratorInfo {
            get {
                return ResourceManager.GetString("DisplayCharacterGeneratorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error..
        /// </summary>
        internal static string ListAllDSAFunctionsError {
            get {
                return ResourceManager.GetString("ListAllDSAFunctionsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error..
        /// </summary>
        internal static string LootChancesError {
            get {
                return ResourceManager.GetString("LootChancesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error..
        /// </summary>
        internal static string MultipleLootStrError {
            get {
                return ResourceManager.GetString("MultipleLootStrError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error..
        /// </summary>
        internal static string RandomLootStrError {
            get {
                return ResourceManager.GetString("RandomLootStrError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;@{0}&gt;rolls for {1}:.
        /// </summary>
        internal static string RollDSABase {
            get {
                return ResourceManager.GetString("RollDSABase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;@{0}&gt; rolled the following:.
        /// </summary>
        internal static string RollDSABaseWithoutTalent {
            get {
                return ResourceManager.GetString("RollDSABaseWithoutTalent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error..
        /// </summary>
        internal static string RollDSAError {
            get {
                return ResourceManager.GetString("RollDSAError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The talent does not exist. Did you mistype?.
        /// </summary>
        internal static string RollDSATalentNonExistent {
            get {
                return ResourceManager.GetString("RollDSATalentNonExistent", resourceCulture);
            }
        }
    }
}
